spring:
  application:
    name: Tessa # 应用名称，用于服务注册与发现
  datasource:
    url: jdbc:mysql://localhost:3306/tessa # 数据库连接URL
    username: root # 数据库用户名
    password: $D:s9whilenhua+e # 数据库密码（建议使用环境变量或配置中心管理）
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL驱动类
    hikari:
      maximum-pool-size: 10 # 最大连接池大小
      connection-timeout: 30000 # 连接超时时间（毫秒）
  data:
    redis:
      host: localhost # Redis服务器地址
      port: 6379 # Redis服务器端口
      password: # Redis密码（如果有）
      timeout: 5000 # 连接超时时间（毫秒）
      database: 0 # 使用的数据库索引
  mail:
    host: smtp.qq.com
    port: 587 # 使用 587 端口 (STARTTLS) 而非 465 (SSL)
    username: noahmiller@qq.com
    password: ittorsxkbstcecha
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

  # 服务启动时的字符画(ASCII ART)
  banner:
    location: banner.txt
mybatis:
  mapper-locations: classpath:mapper/*.xml # Mapper XML文件位置
  type-aliases-package: com.noahmiller.tessa.entity
  configuration:
    log-impl=org:
          apache:
            ibatis:
              logging:
                stdout:
                  StdOutImpl: # 实体类包路径
    # 驼峰式命名的映射
    map-underscore-to-camel-case: true

server:
  port: 80 # 应用服务端口
  servlet:
    context-path: / # 应用上下文路径
  tomcat:
    max-threads: 200 # Tomcat最大线程数
    max-connections: 8192 # Tomcat最大连接数

# 配置日志文件
logging:
  level:
    root: info

    org:
      springframework:
        security: DEBUG # 设置日志级别

  file:
    name: app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# 我的自定义配置
my-configuration:
  security:
    password:
      min-length: 8
      max-length: 32
      pattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^a-zA-Z\d]).{8,}$
  redis:
    key-prefix: "Tessa"
  jwt:
    issuer: Tessa
    secretKey: ${SecretKey:"kW!O7yhl7!hnQjU&qPFwp1#wBdTqtt6LqiN#49n0ITJWmVyX&7NCCEVhGhKs2jfV"}  # 从环境变量获取密钥
    access-expiration: 3600000             # 1小时（毫秒）
    refresh-expiration: 2592000000         # 30天（毫秒）


